/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface XcastvenAmbulanceWlList {
    }
}
declare global {
    interface HTMLXcastvenAmbulanceWlListElement extends Components.XcastvenAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLXcastvenAmbulanceWlListElement: {
        prototype: HTMLXcastvenAmbulanceWlListElement;
        new (): HTMLXcastvenAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "xcastven-ambulance-wl-list": HTMLXcastvenAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface XcastvenAmbulanceWlList {
    }
    interface IntrinsicElements {
        "xcastven-ambulance-wl-list": XcastvenAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "xcastven-ambulance-wl-list": LocalJSX.XcastvenAmbulanceWlList & JSXBase.HTMLAttributes<HTMLXcastvenAmbulanceWlListElement>;
        }
    }
}
